### ISSUE TITLE
The autoformat feature should apply only allowed headings

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-autoformat#17]
After closing https://github.com/ckeditor/ckeditor5-heading/issues/33 the autoformat feature should insert only allowed headers.

**Comment by oskarwrobel** [comment]
Autoformat allows applying headers event when there is no Heading feature defined in editor configuration.

**Comment by Reinmar** [comment]
That's because of https://github.com/ckeditor/ckeditor5-autoformat/issues/5. The autoformat feature loads the other features while it must not do that.

**Comment by oleq** [comment]
Closed in https://github.com/ckeditor/ckeditor5-autoformat/issues/5.
