### ISSUE TITLE
Autoformat is too aggressive

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor5-autoformat#18]
1. Open `ckeditor5-autoformat/tests/manual/autoformat.html` 
2. Type "1939 was an important year in the XX century".

I think it can make sense to autoformat numbers only if they end up with a dot or parenthesis (`1.` or `1)`).

**Comment by oleq** [comment]
I can't reproduce the issue anymore. @wwalc?

**Comment by Reinmar** [comment]
We changed the regexp there some time ago.

**Comment by Reinmar** [comment]
DUP of https://github.com/ckeditor/ckeditor5-autoformat/issues/42
