### ISSUE TITLE
Add support for block quotes

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-autoformat#26]
"> " should start a quote.

**Comment by fredck** [comment]
Shouldn't this be available for the "Quoted Text" feature only, which is still not implemented?

**Comment by Reinmar** [comment]
What's "Quoted Text"? Do you mean pulled quotes?

**Comment by fredck** [comment]
No, there are 3 quote related features:

 * "Block Quote" - quoting a third party in an article.
 * "Pull Quote" - a quote that is a repetition of a small piece of text from the same article.
 * "Quoted Text" - quoting original text when giving a reply, like an e-mail or GH tickets.

AFAIK, we have "Block Quote" implemented so far. I believe that the common practice of using `>` fits only the "Quoted Text" case.

**Comment by Reinmar** [comment]
OK, I got confused y all these names... :D

So... I don't know. I think that the users may be using "> " for both things. And there should be no problem with having autoformatter applying the QT if present or BQ if not.

But I'm also unsure which should have precedence. QT, as you mentioned many times yourself, is done programmatically – by your system when you reply to some message. You can also be doing it manually when copy+pasting some message into your editor. You may, actually, be doing BQ manually more often.

Still, the main point is that BQ and QT will rarely be used together so there's no big issue with having both of them applied on "> ", depending on which is loaded.
