### ISSUE TITLE
Autoformat for headings rely on the heading package too deeply

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-autoformat#29]
The code looks like this now:

```js
	_addHeadingAutoformats() {
		const commands = this.editor.commands;
		const options = this.editor.config.get( 'heading.options' );

		if ( options ) {
			for ( const option of options ) {
				const commandName = option.modelElement;
				let match;

				if ( commands.has( commandName ) && ( match = commandName.match( /\d+$/ ) ) ) {
					const level = match[ 0 ];
					const regExp = new RegExp( `^(#{${ level }})\\s$` );

					// eslint-disable-next-line no-new
					new BlockAutoformatEngine( this.editor, regExp, context => {
						const { batch } = context;

						this.editor.execute( commandName, { batch } );
					} );
				}
			}
		}
	}
```

What I don't understand is why is the autoformat dependent on the config option? Can't it simply depend on commands that it can find? You never know how config option will be turned into commands (if one didn't load the heading plugin there may be no commands despite the config option being set!).

**Comment by szymonkups** [comment]
Heading commands' names are created based on configuration. Command name is same as `modelElement` from configuration. We need to find a way to match regexp with correct level. For example: how to know that `##` should execute `heading2` command? 

I know this is not the best solution but I couldn't find better one.

**Comment by Reinmar** [comment]
We should be looking for `headingN` in the command collection and just use the `N` to know the number of `#` which we look for. Wouldn't that be enough?

**Comment by szymonkups** [comment]
We can go with that. It will just assume that all command names will be in form `headingN` but I think it's not a big deal.

**Comment by Reinmar** [comment]
I think it's a safe assumption. Besides, the heading feature is configured with model->view mapping. So, no matter which heading levels you want to use in the view, you can (and should) always start from `heading1` in the model. The autoformat feature can then base on that.
