### ISSUE TITLE
Italic autoformat does not work in the features sample

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-autoformat#34]
1. Go to https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/autoformat.html.
2. Type `*foo*`.
3. `*` characters are gone.

Expected: `foo` should become italic _foo_.

Actual: Nothing happens.

Note 1.: Bold works as expected.
Note 2.: Italic works in http://localhost:8125/ckeditor5-autoformat/tests/manual/autoformat.html as expected.

**Comment by pomek** [comment]
Something wrong is with the styles. 

![image](https://user-images.githubusercontent.com/2270764/29559394-4a6676d4-872f-11e7-9c1a-947e22a46aa5.png)

**Comment by Reinmar** [comment]
Haha :D That was unexpected.

**Comment by Reinmar** [comment]
I'll be soon fixing style issues in the samples in the docs, so I'll take care of it.

**Comment by scofalik** [comment]
Shouldn't it be converted to `<em>`? Of course this is not only a problem with autoformat feature, but just italic in all the samples.

**Comment by pomek** [comment]
http://ckeditor.github.io/editor-recommendations/features/italic.html

> The `i` element MUST be used to represent the Italic feature, as it’s the element dedicated to mark a a different quality of text, such as taxonomic designation, a technical term or an idiomatic phrase.

**Comment by scofalik** [comment]
Color me surprised. We had `<em>` for a long time. It's even like this on ckeditor5.github.io

**Comment by pomek** [comment]
We had but we changed it – https://github.com/ckeditor/ckeditor5-basic-styles/issues/28 :D
