### ISSUE TITLE
Autoformat Plugin issue

### ISSUE THREAD

**Issue by projjwalmaiti** [ckeditor/ckeditor5-autoformat#45]
Hi,

I am new to this.
I am using the ckeditor5-autoformat plugin.

```
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';

ClassicEditor
    .create( document.querySelector( '#editor' ), {
        plugins: [ Autoformat, ... ],
        toolbar: [ ... ]
    } );
```

Here i am getting an error Autoformat is undefined.

Please help!

**Comment by Reinmar** [comment]
Can you share a stack strace or something too? And more information on how you're building the editor? In other words – all the steps that we need to do in order to reproduce this problem.

**Comment by projjwalmaiti** [comment]
Hi Reinmar,

Thanks for replying.

Please find my google drive attachment 
https://drive.google.com/open?id=12p9GH7WbF-F_BUcjVlBjF8K0f7RRnxM0

Might be i am doing something wrong 
I am new to this you can help me understand what i am doing wrong so we can get it fixed.

Here are my steps

As per https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/advanced-setup.html
   
step 1: 
   
npm install --save @ckeditor/ckeditor5-dev-webpack-plugin css-loader node-sass raw-loader sass-loader style-loader webpack


step 2:
I have made the src folder

step 3:
copied the file ckeditor.js

step 4:
invoking webpack

C:\Npm_package\CKE5>webpack
C:\Npm_package\CKE5\node_modules\@ckeditor\ckeditor5-dev-webpack-plugin\lib\index.js:42
        constructor( options = {} ) {
                             ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Npm_package\CKE5\webpack.config.js:1:93)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

Thanks!

**Comment by Reinmar** [comment]
Hi! I'm sorry for a very later reply, but we missed your message.

Were you able to resolve this issue?

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
