### ISSUE TITLE
The Autoformat feature should not require the Bold, Italic, etc. features

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-autoformat#5]
The idea was that it will enable autoformatting for the other features, if they are enabled.

This means that we need to check whether the other features are enabled. I thought that we'd be able to do that in the `Autoformat.init()` method,  but unfortunately, this won't be reliable. We need to check this later on, on the runtime. Alternatively, we need to introduce some "post init" event in the editor.

**Comment by Reinmar** [comment]
There's another issue caused by this: https://github.com/ckeditor/ckeditor5-heading/issues/40.

**Comment by Reinmar** [comment]
Remember about cleaning up package dependencies after fixing this.

**Comment by pjasiun** [comment]
Similar: https://github.com/ckeditor/ckeditor5-autoformat/issues/17.

**Comment by Reinmar** [comment]
This issue can be easily fixed now, because we have `Plugin#afterInit`.
