### ISSUE TITLE
[FF] Unable to type a space after autoformatting 

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-autoformat#58]
1. Open the feature guide http://localhost/cke5/_/build/docs/ckeditor5/latest/features/autoformat.html.
2. Empty the editable.
3. Type `*foo*`
4. Press <kbd>Space</kbd>

**Expected**: `<p><i>foo</i> []</p>`

**Actual**: `<p><i>foo</i>[]</p>`

Successive <kbd>Space</kbd> presses make no difference. The caret is stuck for all inline autoformats.

**Comment by oleq** [comment]
Update, it's far beyond autoformat:

1. Press bold (on),
2. Type "a",
3. Press bold (off),
4. Press <kbd>Space</kbd>

**Expected**: `<p><b>a</b> []</p>`

**Actual**: `<p><b>a</b>[]</p>`

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5/issues/1083.
