### ISSUE TITLE
Make basic styles autoformat implementations execute commands

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-autoformat#70]
Instead of setting attribute by hand, `InlineAutoformatEditing` implementations should use `command.execute()` to provide better integration possibilities with other parts of the editor.

**Comment by scofalik** [comment]
Unfortunately, the side effect of this change without any other changes is this issue: https://github.com/ckeditor/ckeditor5-undo/issues/44.

**Comment by Reinmar** [comment]
DUP of https://github.com/ckeditor/ckeditor5-autoformat/issues/7.
