### ISSUE TITLE
ckeditor5: any strings followed by hyphen are converted to numbered list 

### ISSUE THREAD

**Issue by danyal14** [ckeditor/ckeditor5-autoformat#73]
When starting sentence or paragraph with hyphen (-), editor converts it to unordered list

**Comment by Mgsy** [comment]
Hello, this behaviour occurs because of the autoformat plugin. If you want to disable changing `-` to the unordered list, you have two ways:
* Disable the plugin
* Press <kbd>Ctrl + Z</kbd> to undo the formatting action, so you'll finish with `-`

**Comment by scofalik** [comment]
Another solution would be to start the sentence with a space character before hypen but it is not a good solution either.
