### ISSUE TITLE
Misses 100% CC

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-autoformat#9]
There are few conditions without CC.

**Comment by szymonkups** [comment]
I was almost sure it had 100% CC, just checked it again:
![image](https://cloud.githubusercontent.com/assets/2396463/19920023/92e7f044-a0d6-11e6-8a11-e20010896e71.png)

Did You use `tag:module!autoformat`?

**Comment by Reinmar** [comment]
I don't know... I mean – I was 100% sure it had 100% CC when R+ing, but then I had constantly a lower result. Let me check this today... :D

**Comment by Reinmar** [comment]
100%CC today :) Sorry.
